### ISSUE TITLE
Control Tuya RGB (W or C or CW)  from localtuya

### ISSUE THREAD

**Issue by DavidFFerreira** [rospogrigio/localtuya#33]
Control Tuya RGB (W or C or CW)  from localtuya
I have several bubs from tuya with RGB + WC and RGB + WW and bought configuration
Just tell me what I need to test to send you feedback for you can accomplish this

**Comment by postlund** [comment]
We would need the DPS list for your device to start with. There is support for the `light` platform already, but I can't vouch for its condition. I believe it's pretty broken on `master` right now, but I'm cleaning it up right now so maybe we have something you can try out soon. If you don't have a `local_key`, you can start with that (see [here](https://github.com/codetheweb/tuyapi/blob/master/docs/SETUP.md) for instance)

**Comment by brutegreen** [comment]
Hey guys,
Firstly - apologies if this isn't the correct place for this info.

I actually started working on trying to get my [Arlec RGB + CCT bulb](https://www.bunnings.com.au/arlec-grid-connect-smart-9w-806lm-rgb-cct-bc-b22-globe_p0111500) (Tuya Smart Life compatible) working last night and have just seen there are active changes being made. 

Using the latest commit from master and the below changes, I was able to get my bulb added to HA, and working for turning off and on and setting brightness. The option for RGB is displayed in HA but returns the "TODO implement RGB from HA" error (as expected).

**Changes to ```light.py``` to get light working in HA**
* Change values for DPS_INDEX_ constants from 1-5 to 20-24
* Fix line 74 to use ```TuyaDevice``` not ```TuyaCache```
* Change lines 143, 163, and 167 to use ```DPS_INDEX_ON``` instead of ```self._dps_index```


If it is helpful, I get the following dsp results for the various different states:
**100% Brightness, Full Cool White**
```"dps":{"20":true,"21":"white","22":1000,"23":1000,"24":"00f003e803e8","25":"000e0d0000000000000000c80000","26":0}'```

**50% Brightness, Full Cool White**
```"dps":{"20":true,"21":"white","22":500,"23":1000,"24":"00f003e803e8","25":"000e0d0000000000000000c80000","26":0}'```

**1% Brightness (lowest setting), Full Cool White**
```"dps":{"20":true,"21":"white","22":10,"23":1000,"24":"00f003e803e8","25":"000e0d0000000000000000c80000","26":0}'```

**100% Brightness, Full Warm White**
```"dps":{"20":true,"21":"white","22":1000,"23":0,"24":"00f003e803e8","25":"000e0d0000000000000000c80000","26":0}```

**50% Brightness, Full Warm White**
```"dps":{"20":true,"21":"white","22":500,"23":0,"24":"00f003e803e8","25":"000e0d0000000000000000c80000","26":0}```

**1% Brightness, Full Warm White**
```"dps":{"20":true,"21":"white","22":10,"23":0,"24":"00f003e803e8","25":"000e0d0000000000000000c80000","26":0}```

**100% Brightness, Full Red**
```"dps":{"20":true,"21":"colour","22":500,"23":0,"24":"000003e803e8","25":"000e0d0000000000000000c80000","26":0}```

**50% Brightness, Full Red**
```"dps":{"20":true,"21":"colour","22":500,"23":0,"24":"000003e801f4","25":"000e0d0000000000000000c80000","26":0}```

**1% Brightness (lowest setting), Full Red**
```"dps":{"20":true,"21":"colour","22":500,"23":0,"24":"000003e8000a","25":"000e0d0000000000000000c80000","26":0}```

**100% Brightness, Full Green**
```"dps":{"20":true,"21":"colour","22":500,"23":0,"24":"007803e803e8","25":"000e0d0000000000000000c80000","26":0}```

**50% Brightness, Full Green**
```"dps":{"20":true,"21":"colour","22":500,"23":0,"24":"007803e801f4","25":"000e0d0000000000000000c80000","26":0}```

**1% Brightness (lowest setting), Full Green**
```"dps":{"20":true,"21":"colour","22":500,"23":0,"24":"007803e8000a","25":"000e0d0000000000000000c80000","26":0}```

**100% Brightness, Full Blue**
```"dps":{"20":true,"21":"colour","22":500,"23":0,"24":"00f003e803e8","25":"000e0d0000000000000000c80000","26":0}```

**50% Brightness, Full Blue
```"dps":{"20":true,"21":"colour","22":500,"23":0,"24":"00f003e801f4","25":"000e0d0000000000000000c80000","26":0}```

**1% Brightness (lowest setting), Full Blue**
```"dps":{"20":true,"21":"colour","22":500,"23":0,"24":"00f003e8000a","25":"000e0d0000000000000000c80000","26":0}```

Again, apologies if this wasn't the correct place for this - this issue seemed relevant to what I was doing but please let me know if I should be creating a different Issue or something.

Also, please let me know if there are any additional details you would like, or changes you'd like me to investigate. I believe the previous commit had a HEX to HSV method so I will take a look there next to see if I can get the RGB get/set working.

Cheers.

**Comment by postlund** [comment]
This is a good place to comment on this 😊

Since you had to change the `DPS_INDEX_` constants, we need to add options for them. That's quite easy to to. The `self._dps_index` variable contains whatever is specified in `id` (YAML) or whatever you picked for ID in the config flow. So you should be able to fix this from your configuration rather than change in code.

Would be awesome if you could get cracking on RGB support. As you mentioned, there were a few helper methods for color conversions before (but removed now due to not used). They are here (roughly):

https://github.com/rospogrigio/localtuya-homeassistant/blob/eca400f5810119925cde1b948e9b415c545d0e26/custom_components/localtuya/pytuya/__init__.py#L563

You also have a few helper methods in Home Assistant that you can pull in, if they are useful:

https://github.com/home-assistant/core/blob/dev/homeassistant/util/color.py

**Comment by brutegreen** [comment]
Hey, thanks for the feedback.

I have fixed my YAML to include the correct ```id```.  When you say "add options" for the other ```DPS_INDEX_``` values, do you mean adding config options for those, or something else?

At this point I have got the RGB working for my bulb. I can use the lovelace interface to switch between ```white``` mode with color temp selection, and ```colour``` mode with full RGB control. Given the bulb has to be set to one of the two modes, I have currently got it switching modes based on whether a color_temp (mode = ```white```) or hs_color (mode = ```colour```) is sent from HA. Open to suggestions if there is a better approach.

FYI, the hex value for the colour (DPS "24" in my examples) is an HSV colour encoded as:
```
xxxxxxxxxxxx
└┬─┘└┬─┘└┬─┘
 h   s   v
```
where:
* h is the Hue (with a range 0-360) in Hex padded to 4 characters
* s is the Saturation (with a range 0-1000) in Hex padded to 4 characters
* v is the Value a.k.a brightness (with a range 0-1000) in Hex padded to 4 characters

Still to go:
* Get the color_temp working correctly (currently not utilizing the full range)
* Get the supported_features working correctly (had to hard code at this point)
* Tidy up the code a little

Once the above are done I will try to create a pull request to share the progress.

I also have a couple of RGBW bulbs on the way, so when they arrive I will investigate their DPS details and see how they compare.

**Comment by postlund** [comment]
Yeah, I meant that we need to expose those datapoints as settings that can be overridden in the config (be it YAML or config flow). I created #47 which makes it possible to specify `brightness` and `color_temp` with the DP you need. The same thing can be done with config flow too. Please give it a try and let me know if it works. It can serve as some inspiration in case you need to add another option.

**Comment by brutegreen** [comment]
Awesome - that's exactly what I had started doing. Glad I was on the right track.

**Comment by postlund** [comment]
@brutegreen If you can confirm that #47 works as expected, then maybe we should go ahead and merge?

**Comment by DavidFFerreira** [comment]
I think you should do more tests, because light bulbs have RGB only, RGB+C, RGB +W, RGB+c+w

**Comment by DavidFFerreira** [comment]
I have all, i Think....just tell me how to tested lol

**Comment by brutegreen** [comment]
@postlund I will pull #47 into my repo and test as soon as I can. Unfortunately I won't get a chance now for a few days, but will do it as soon as I can and confirm.

@DavidFFerreira Yes, there'll definitely be more work required. I am thinking there may need to be a config option to specify the bulb type. Either that or the DPS index values being set in the config will inform what features are available (but that puts a bit more onus on the user to configure the device correctly). I haven't yet seen how to retrieve the bulb type and/or features from the device itself (although to be fair I haven't spent a lot of time on it).
I have some RGBW on their way so will start testing those when they arrive, but until then I am limited in testing (and coding to) the device I have which is a RGBCCT bulb. If you are able to supply the DPS values for the bulbs you have, that'd be a massive help (e.g. see my first comment in this thread).
To get those values, follow the 'Usage' instructions (in this repo's README.md) to get the device connected to HA, then retrieve the decrypted result from your log.

Cheers.

**Comment by ultratoto14** [comment]
Just to add a point, i just ordered two LSC Smart connect king of RGBW lights.

- A led strip that is using DPS 20-24 range to set color and brightness as mentioned above. Brightness and color temp on a range 10 - 1000, color coded on hsv.

- Some GU10 RGBW using 1-5 range, Brightness and color temp on a range 0 - 255, color is coded as explained [there ](https://github.com/clach04/python-tuya/blob/master/pytuya/__init__.py#L412)

I made some dirty changes to your component to make the GU10 working, almost everything, just need to manage the brightness when in color mode. I'm afraid that we will need a lot of configuration options for the different bulbs, maybe it can be automatically discovered.

**Comment by danVnest** [comment]
I'm also looking at this at the moment - making progress but not quite there yet.
Thought I'd add some notes here in case it's useful for others.

I pulled #47 but had to make some changes:
- Included support for color temp instead of color which is not implemented yet - see #48. This changes what is shown for the entity in the Home Assistant UI.
- My LED strip's brightness ranges from 10 - 1000 just like @ultratoto14 mentioned, adjusted this in `turn_on` and `status_updated` and it works.
- color_temp ranges from 0 - 1000, again adjusted and it works.

The different value ranges for different devices will either require additional config options, or we could perhaps auto-detect bounds in the `status_updated` function by manually changing the light's values from min to max via the Tuya app?

From the limited testing I've done in the last half an hour, it works most of the time. Occasionally get delays or missed commands, `[custom_components.localtuya] Failed to set status of device 192.168.01.23` in the logs. Will try and determine what the cause of that is.

**Comment by ultratoto14** [comment]
@danVnest as for the moment, we only know these two ranges 0-1000 and 0-255. During the light detection it could be easy to test if setting 1000 is possible and chose 255 if not. (As a first implementation)

Maybe the delays or missed command is linked to:

- Seems that the bulbs accept only one TCP connection at a time, if you have the mobile application running...
- It seems that all the orders are sent one by one, tuya can accept multiple orders in the same message but it does not seem to be implemented in this repo yet.

I also have a concern about the brightness. When you switch from color to white or white to color you can have very huge differences as the brightness is managed completely differently.

In 20-24 dps kind:

- color is dps 24  in format  `"0[hhh]0[sss]0[vvv]"` where vvv is like brightness and is in range 0-1000
- white dps 23 is color temp and brightness on 22

In  1-5 dps kind
- color is dps 5  in format  `"[rr][gg][bb]00ffff[bb]"` where the last two [bb] is brightness 0-255. r,g and b are 0-255 two
- white dps 3 is color temp and brightness on 2

What i do is ensuring that when we toggle from white to colour and the opposite, i keep the brightness at the same level, preventing going from a soft color light to a full white light per exemple.

**Comment by postlund** [comment]
Our current implementation in pytuya is extremely basic and limited. I will try to "polish it" a bit once the rest of the integration is in a good shape. Hopefully we should be there quite soon.

One of the side-effects with the design I've used is that everything is very generic. So we *will* need to provide config options for pretty much anything the is different amongst manufacturers, unless options are available via a DP. The benefit on the other hand is that we can support more or less anything. In the future, maybe we can add some kind of "template" devices or even create a database of known devices so that these can be set up automatically. But for now we will have to manually configure a lot of stuff.

**Comment by danVnest** [comment]
Thanks @ultratoto14, the following does seem to be the case:
> * Seems that the bulbs accept only one TCP connection at a time, if you have the mobile application running...

Looks like most of the work here is going into colour control.
Would it be worthwhile if I submitted a pull request that handles devices with 255 or 1000 limits (and config options for max/min mireds)?

**Comment by ultratoto14** [comment]
@danVnest i put something there [Manage RGBW tuya lights](https://github.com/ultratoto14/localtuya-homeassistant/commit/0ea5661a70566b636d8a443f4be100aaffa5ee19)

This is quick and dirty but it handles almost everything for the 1-5 dps range. Perhaps this can help for a better integration.

**Comment by DavidFFerreira** [comment]
Yes I can, just tell me how xD lol
I have bulbs with only RGB , RGB + CW+ WW, RGB +CW and RGB + WW. There is a few diferences in mainboard. Some are 1.0.0.7 anothers are 3.3.3.5. Also the tuya app is diferent when I select with a diferent board. Also I cant group 2 diferent types of bulgs in Tuya, imagine that xD

> @postlund I will pull #47 into my repo and test as soon as I can. Unfortunately I won't get a chance now for a few days, but will do it as soon as I can and confirm.
> 
> @DavidFFerreira Yes, there'll definitely be more work required. I am thinking there may need to be a config option to specify the bulb type. Either that or the DPS index values being set in the config will inform what features are available (but that puts a bit more onus on the user to configure the device correctly). I haven't yet seen how to retrieve the bulb type and/or features from the device itself (although to be fair I haven't spent a lot of time on it).
> I have some RGBW on their way so will start testing those when they arrive, but until then I am limited in testing (and coding to) the device I have which is a RGBCCT bulb. If you are able to supply the DPS values for the bulbs you have, that'd be a massive help (e.g. see my first comment in this thread).
> To get those values, follow the 'Usage' instructions (in this repo's README.md) to get the device connected to HA, then retrieve the decrypted result from your log.
> 
> Cheers.

**Comment by postlund** [comment]
We should try to get this rolling again, supporting RGB would be great! I have prepared a name change for `set_dps` to `set_dp`, which allows us to use `set_dps` to set multiple datapoints at once. It's in #83. I also think I have fixed the brightness range and made a few clean ups in the light platform in #80. So with these as base we should be able to move on.

@ultratoto14 Would be great if you could bump your code to master and submit a PR so we can get cracking. I can review.

**Comment by bepece1** [comment]
> Hey guys,
> Firstly - apologies if this isn't the correct place for this info.
> 
> I actually started working on trying to get my [Arlec RGB + CCT bulb](https://www.bunnings.com.au/arlec-grid-connect-smart-9w-806lm-rgb-cct-bc-b22-globe_p0111500) (Tuya Smart Life compatible) working last night and have just seen there are active changes being made.
> 
> Using the latest commit from master and the below changes, I was able to get my bulb added to HA, and working for turning off and on and setting brightness. The option for RGB is displayed in HA but returns the "TODO implement RGB from HS" error (as expected).
> 
> **Changes to `light.py` to get light working in HA**
> 
> * Change values for DPS_INDEX_ constants from 1-5 to 20-24
> * Fix line 74 to use `TuyaDevice` not `TuyaCache`
> * Change lines 143, 163, and 167 to use `DPS_INDEX_ON` instead of `self._dps_index`
> 
> If it is helpful, I get the following dsp results for the various different states:
> **100% Brightness, Full Cool White**
> `"dps":{"20":true,"21":"white","22":1000,"23":1000,"24":"00f003e803e8","25":"000e0d0000000000000000c80000","26":0}'`
> 
> **50% Brightness, Full Cool White**
> `"dps":{"20":true,"21":"white","22":500,"23":1000,"24":"00f003e803e8","25":"000e0d0000000000000000c80000","26":0}'`
> 
> **1% Brightness (lowest setting), Full Cool White**
> `"dps":{"20":true,"21":"white","22":10,"23":1000,"24":"00f003e803e8","25":"000e0d0000000000000000c80000","26":0}'`
> 
> **100% Brightness, Full Warm White**
> `"dps":{"20":true,"21":"white","22":1000,"23":0,"24":"00f003e803e8","25":"000e0d0000000000000000c80000","26":0}`
> 
> **50% Brightness, Full Warm White**
> `"dps":{"20":true,"21":"white","22":500,"23":0,"24":"00f003e803e8","25":"000e0d0000000000000000c80000","26":0}`
> 
> **1% Brightness, Full Warm White**
> `"dps":{"20":true,"21":"white","22":10,"23":0,"24":"00f003e803e8","25":"000e0d0000000000000000c80000","26":0}`
> 
> **100% Brightness, Full Red**
> `"dps":{"20":true,"21":"colour","22":500,"23":0,"24":"000003e803e8","25":"000e0d0000000000000000c80000","26":0}`
> 
> **50% Brightness, Full Red**
> `"dps":{"20":true,"21":"colour","22":500,"23":0,"24":"000003e801f4","25":"000e0d0000000000000000c80000","26":0}`
> 
> **1% Brightness (lowest setting), Full Red**
> `"dps":{"20":true,"21":"colour","22":500,"23":0,"24":"000003e8000a","25":"000e0d0000000000000000c80000","26":0}`
> 
> **100% Brightness, Full Green**
> `"dps":{"20":true,"21":"colour","22":500,"23":0,"24":"007803e803e8","25":"000e0d0000000000000000c80000","26":0}`
> 
> **50% Brightness, Full Green**
> `"dps":{"20":true,"21":"colour","22":500,"23":0,"24":"007803e801f4","25":"000e0d0000000000000000c80000","26":0}`
> 
> **1% Brightness (lowest setting), Full Green**
> `"dps":{"20":true,"21":"colour","22":500,"23":0,"24":"007803e8000a","25":"000e0d0000000000000000c80000","26":0}`
> 
> **100% Brightness, Full Blue**
> `"dps":{"20":true,"21":"colour","22":500,"23":0,"24":"00f003e803e8","25":"000e0d0000000000000000c80000","26":0}`
> 
> **50% Brightness, Full Blue
> `"dps":{"20":true,"21":"colour","22":500,"23":0,"24":"00f003e801f4","25":"000e0d0000000000000000c80000","26":0}`
> 
> **1% Brightness (lowest setting), Full Blue**
> `"dps":{"20":true,"21":"colour","22":500,"23":0,"24":"00f003e8000a","25":"000e0d0000000000000000c80000","26":0}`
> 
> Again, apologies if this wasn't the correct place for this - this issue seemed relevant to what I was doing but please let me know if I should be creating a different Issue or something.
> 
> Also, please let me know if there are any additional details you would like, or changes you'd like me to investigate. I believe the previous commit had a HEX to HSV method so I will take a look there next to see if I can get the RGB get/set working.
> 
> Cheers.

work rgb in HA now???

**Comment by postlund** [comment]
> work rgb in HA now???

Not yet, I'm working on it.

**Comment by SmartM-ui** [comment]
I follow with interest ...

**Comment by postlund** [comment]
I have created a PR, #90, with start to support colors. Only HSV encoded colors are supported so far, since @br

**Comment by postlund** [comment]
I have uploaded #90 with initial support for colors. Only colors encoded in HSV format are supported for now, will do RGB later. I believe it matches examples from @brutegreen early in the thread, but I don't know for sure (I don't have any hardware to test with). Just hitting the keyboard until something happens 🤷

**Comment by SmartM-ui** [comment]
Thanks Pierre,
as soon as I get home (I'm on vacation) I carry out some tests and provide the data.
Having still installed the custom TuyaConvert (which reports the color data), can I be useful by carrying out some specific tests to compare the data?

Good luck for this new beginning :-)

**Comment by accelle17** [comment]
> I have uploaded #90 with initial support for colors. Only colors encoded in HSV format are supported for now, will do RGB later. I believe it matches examples from @brutegreen early in the thread, but I don't know for sure (I don't have any hardware to test with). Just hitting the keyboard until something happens 🤷

was working for me, I only mapped the HSV, no brightness or temperature.Iit was able to set the color instantaneously but the entity state goes from unavailable to on and it require some time for the UI color to reflect.

Here's the error

> 2020-10-18 21:29:14 DEBUG (MainThread) [custom_components.localtuya.pytuya] [ebb2e815c7c80a5fc4cq0v] Sending command heartbeat (device type: type_0a)
2020-10-18 21:29:14 DEBUG (MainThread) [custom_components.localtuya.pytuya] [ebb2e815c7c80a5fc4cq0v] Paylod: b'{}'
2020-10-18 21:29:14 DEBUG (MainThread) [custom_components.localtuya.pytuya] [ebb2e815c7c80a5fc4cq0v] Waiting for sequence number -100
2020-10-18 21:29:14 DEBUG (MainThread) [custom_components.localtuya.pytuya] [ebb2e815c7c80a5fc4cq0v] Got heartbeat response
2020-10-18 21:29:14 DEBUG (MainThread) [custom_components.localtuya.pytuya] [ebb2e815c7c80a5fc4cq0v] Decode payload: b''
2020-10-18 21:29:14 DEBUG (MainThread) [custom_components.localtuya.pytuya] [ebb2e815c7c80a5fc4cq0v] Decrypted payload: {}
2020-10-18 21:29:30 DEBUG (MainThread) [custom_components.localtuya.pytuya] [ebb2e815c7c80a5fc4cq0v] Sending command set (device type: type_0a)
2020-10-18 21:29:30 DEBUG (MainThread) [custom_components.localtuya.pytuya] [ebb2e815c7c80a5fc4cq0v] Paylod: b'{"devId":"ebb2e815c7c80a5fc4cq0v","uid":"ebb2e815c7c80a5fc4cq0v","t":"1603027770","dps":{"103":true}}'
2020-10-18 21:29:30 DEBUG (MainThread) [custom_components.localtuya.pytuya] [ebb2e815c7c80a5fc4cq0v] Waiting for sequence number 8
2020-10-18 21:29:30 DEBUG (MainThread) [custom_components.localtuya.pytuya] [ebb2e815c7c80a5fc4cq0v] Got status update
2020-10-18 21:29:30 DEBUG (MainThread) [custom_components.localtuya.pytuya] [ebb2e815c7c80a5fc4cq0v] Decode payload: b'3.3\x00\x00\x00\x00\x00\x00%\xe7\x00\x00\x00\x01\xe8N\x01\x05\xc1\xb2\x92m\xcdN\x0e\xe7\x88\xec\x16\xb5\xec\xdd\x90\xf8\xcd\x90p\xab\x08cQ\x93\x17\xfa\xc8?'
2020-10-18 21:29:30 DEBUG (MainThread) [custom_components.localtuya.pytuya] [ebb2e815c7c80a5fc4cq0v] Decrypted payload: {"dps":{"103":true},"t":22912}
2020-10-18 21:29:30 DEBUG (MainThread) [custom_components.localtuya.pytuya] [ebb2e815c7c80a5fc4cq0v] Got status update
2020-10-18 21:29:30 DEBUG (MainThread) [custom_components.localtuya.pytuya] [ebb2e815c7c80a5fc4cq0v] Decode payload: b'3.3\x00\x00\x00\x00\x00\x00%\xe8\x00\x00\x00\x01j\xa6\xbe\x9b\xd1\xa8{S,\xa5\xb3\x83/\xa4ZVJ3_W5\xc0\xde\xa6\xf5^\x0cC\xe2W\xc4\xc5l\tr\xd57\xf4\xb2\x84\xb6\xea\x8e\x96\x9aF\x9e%zHw\x01\x13\xbblSh\x00\xb0\xca:\x86ti\x1c\xb62Y}\xcc\x9bX\x08?\x9a#\xd3\x1dz\x15a+Sd$\xaf\xdc\x1e\x92[f)G\x90\xd1\xd4\x1e\xa51\x0e\x93&NUT\x9f/\xbe\x17?\x9b\xd9\x15\xde\x0bI\xe4z^\xfe\xec\xae\xef^\x99\x8e7\xa8t\xebR\x8c@\xcc\xf3\x85\x19\xbaz\xb2\xd7\xef\xda\x94\x8d\x10\x99n\xb16C\x8f\x1c\xc7+\x8e\x19\x10\x8aM'
2020-10-18 21:29:30 DEBUG (MainThread) [custom_components.localtuya.pytuya] [ebb2e815c7c80a5fc4cq0v] Decrypted payload: {"dps":{"20":true,"21":"colour","22":1000,"24":"00f003e80320","25":"000e0d00002e03e802cc00000000","101":1000,"102":true,"103":true,"26":0},"t":22912}
2020-10-18 21:29:30 DEBUG (MainThread) [custom_components.localtuya.pytuya] [ebb2e815c7c80a5fc4cq0v] Got message type 12 for unknown listener 7: TuyaMessage(seqno=7, cmd=12, retcode=579904508, payload=b'', crc=12)
2020-10-18 21:29:34 DEBUG (MainThread) [custom_components.localtuya.pytuya] [ebb2e815c7c80a5fc4cq0v] Sending command heartbeat (device type: type_0a)
2020-10-18 21:29:34 DEBUG (MainThread) [custom_components.localtuya.pytuya] [ebb2e815c7c80a5fc4cq0v] Paylod: b'{}'
2020-10-18 21:29:34 DEBUG (MainThread) [custom_components.localtuya.pytuya] [ebb2e815c7c80a5fc4cq0v] Waiting for sequence number -100
2020-10-18 21:29:34 DEBUG (MainThread) [custom_components.localtuya.pytuya] [ebb2e815c7c80a5fc4cq0v] Got message type 21930 for unknown listener 43605: TuyaMessage(seqno=43605, cmd=21930, retcode=9, payload=b'', crc=21930)
2020-10-18 21:29:35 ERROR (MainThread) [custom_components.localtuya.common] Failed to set DP 103 to 1
Traceback (most recent call last):
  File "/config/custom_components/localtuya/common.py", line 178, in set_dp
    await self._interface.set_dp(state, dp_index)
  File "/config/custom_components/localtuya/pytuya/__init__.py", line 444, in set_dp
    return await self.exchange(SET, {str(dp_index): value})
  File "/config/custom_components/localtuya/pytuya/__init__.py", line 406, in exchange
    msg = await self.dispatcher.wait_for(seqno)
  File "/config/custom_components/localtuya/pytuya/__init__.py", line 206, in wait_for
    await asyncio.wait_for(self.listeners[seqno].acquire(), timeout=timeout)
  File "/usr/local/lib/python3.8/asyncio/tasks.py", line 490, in wait_for
    raise exceptions.TimeoutError()
asyncio.exceptions.TimeoutError
2020-10-18 21:29:35 ERROR (MainThread) [custom_components.localtuya.light] COLOR: 007803e80320
2020-10-18 21:29:35 DEBUG (MainThread) [custom_components.localtuya.pytuya] [ebb2e815c7c80a5fc4cq0v] Sending command set (device type: type_0a)
2020-10-18 21:29:35 DEBUG (MainThread) [custom_components.localtuya.pytuya] [ebb2e815c7c80a5fc4cq0v] Paylod: b'{"devId":"ebb2e815c7c80a5fc4cq0v","uid":"ebb2e815c7c80a5fc4cq0v","t":"1603027775","dps":{"24":"007803e80320"}}'
2020-10-18 21:29:35 DEBUG (MainThread) [custom_components.localtuya.pytuya] [ebb2e815c7c80a5fc4cq0v] Waiting for sequence number 10
2020-10-18 21:29:39 ERROR (MainThread) [custom_components.localtuya.pytuya] [ebb2e815c7c80a5fc4cq0v] Heartbeat failed (), disconnecting
Traceback (most recent call last):
  File "/config/custom_components/localtuya/pytuya/__init__.py", line 345, in heartbeat_loop
    await self.heartbeat()
  File "/config/custom_components/localtuya/pytuya/__init__.py", line 434, in heartbeat
    return await self.exchange(HEARTBEAT)
  File "/config/custom_components/localtuya/pytuya/__init__.py", line 406, in exchange
    msg = await self.dispatcher.wait_for(seqno)
  File "/config/custom_components/localtuya/pytuya/__init__.py", line 206, in wait_for
    await asyncio.wait_for(self.listeners[seqno].acquire(), timeout=timeout)
  File "/usr/local/lib/python3.8/asyncio/tasks.py", line 490, in wait_for
    raise exceptions.TimeoutError()
asyncio.exceptions.TimeoutError
2020-10-18 21:29:39 DEBUG (MainThread) [custom_components.localtuya.pytuya] [ebb2e815c7c80a5fc4cq0v] Stopped heartbeat loop
2020-10-18 21:29:39 DEBUG (MainThread) [custom_components.localtuya.pytuya] [ebb2e815c7c80a5fc4cq0v] Closing connection
2020-10-18 21:29:39 DEBUG (MainThread) [custom_components.localtuya.pytuya] [ebb2e815c7c80a5fc4cq0v] Connection lost: None
2020-10-18 21:29:39 DEBUG (MainThread) [custom_components.localtuya.pytuya] [ebb2e815c7c80a5fc4cq0v] Closing connection
2020-10-18 21:29:39 DEBUG (MainThread) [custom_components.localtuya.common] Disconnected from ebb2e815c7c80a5fc4cq0v: None
2020-10-18 21:29:39 DEBUG (MainThread) [custom_components.localtuya.common] Connecting to 192.168.20.49 (ebb2e815c7c80a5fc4cq0v)
2020-10-18 21:29:39 DEBUG (MainThread) [custom_components.localtuya.common] Waiting 0 seconds before connecting
2020-10-18 21:29:39 DEBUG (MainThread) [custom_components.localtuya.pytuya] [ebb2e815c7c80a5fc4cq0v] Wait was aborted for seqno 10
2020-10-18 21:29:39 DEBUG (MainThread) [custom_components.localtuya.common] Connecting to 192.168.20.49
2020-10-18 21:29:39 DEBUG (MainThread) [custom_components.localtuya.pytuya] [ebb2e815c7c80a5fc4cq0v] Started heartbeat loop
2020-10-18 21:29:39 DEBUG (MainThread) [custom_components.localtuya.pytuya] [ebb2e815c7c80a5fc4cq0v] Sending command heartbeat (device type: type_0a)
2020-10-18 21:29:39 DEBUG (MainThread) [custom_components.localtuya.pytuya] [ebb2e815c7c80a5fc4cq0v] Paylod: b'{}'
2020-10-18 21:29:39 DEBUG (MainThread) [custom_components.localtuya.pytuya] [ebb2e815c7c80a5fc4cq0v] Waiting for sequence number -100
2020-10-18 21:29:39 DEBUG (MainThread) [custom_components.localtuya.common] Retrieving initial state
2020-10-18 21:29:39 DEBUG (MainThread) [custom_components.localtuya.pytuya] [ebb2e815c7c80a5fc4cq0v] Sending command status (device type: type_0a)
2020-10-18 21:29:39 DEBUG (MainThread) [custom_components.localtuya.pytuya] [ebb2e815c7c80a5fc4cq0v] Paylod: b'{"gwId":"ebb2e815c7c80a5fc4cq0v","devId":"ebb2e815c7c80a5fc4cq0v"}'
2020-10-18 21:29:39 DEBUG (MainThread) [custom_components.localtuya.pytuya] [ebb2e815c7c80a5fc4cq0v] Waiting for sequence number 1
2020-10-18 21:29:39 DEBUG (MainThread) [custom_components.localtuya.pytuya] [ebb2e815c7c80a5fc4cq0v] Got heartbeat response
2020-10-18 21:29:39 DEBUG (MainThread) [custom_components.localtuya.pytuya] [ebb2e815c7c80a5fc4cq0v] Decode payload: b''
2020-10-18 21:29:39 DEBUG (MainThread) [custom_components.localtuya.pytuya] [ebb2e815c7c80a5fc4cq0v] Decrypted payload: {}
2020-10-18 21:29:39 DEBUG (MainThread) [custom_components.localtuya.pytuya] [ebb2e815c7c80a5fc4cq0v] Dispatching sequence number 1
2020-10-18 21:29:39 DEBUG (MainThread) [custom_components.localtuya.pytuya] [ebb2e815c7c80a5fc4cq0v] Decode payload: b'j\xa6\xbe\x9b\xd1\xa8{S,\xa5\xb3\x83/\xa4ZVJ3_W5\xc0\xde\xa6\xf5^\x0cC\xe2W\xc4\xc5l\tr\xd57\xf4\xb2\x84\xb6\xea\x8e\x96\x9aF\x9e%\xd6\xfc\xea\xcdb\x00kX\x03\x19\x0f0L\xfct\xd3\x1c\xb62Y}\xcc\x9bX\x08?\x9a#\xd3\x1dz\x15a+Sd$\xaf\xdc\x1e\x92[f)G\x90\xd1\xd4\xd4\x82!\xa7\x06R\xd1r\x88\x0e\xa5\xaf\x13\x9a\xd2\x08;\xcc`I\x1fT&\x8cL~\x95\xe4+\xd8\x088&\xc5v\xf2\xc0\xd4\xc92\xad\x12\x1c7\xae\x01\x02\x0c'
2020-10-18 21:29:39 DEBUG (MainThread) [custom_components.localtuya.pytuya] [ebb2e815c7c80a5fc4cq0v] Decrypted payload: {"dps":{"20":true,"21":"colour","22":1000,"24":"007803e80320","25":"000e0d00002e03e802cc00000000","26":0,"101":1000,"102":true,"103":true}}
2020-10-18 21:29:59 DEBUG (MainThread) [custom_components.localtuya.pytuya] [ebb2e815c7c80a5fc4cq0v] Sending command heartbeat (device type: type_0a)
2020-10-18 21:29:59 DEBUG (MainThread) [custom_components.localtuya.pytuya] [ebb2e815c7c80a5fc4cq0v] Paylod: b'{}'
2020-10-18 21:29:59 DEBUG (MainThread) [custom_components.localtuya.pytuya] [ebb2e815c7c80a5fc4cq0v] Waiting for sequence number -100
2020-10-18 21:29:59 DEBUG (MainThread) [custom_components.localtuya.pytuya] [ebb2e815c7c80a5fc4cq0v] Got heartbeat response
2020-10-18 21:29:59 DEBUG (MainThread) [custom_components.localtuya.pytuya] [ebb2e815c7c80a5fc4cq0v] Decode payload: b''
2020-10-18 21:29:59 DEBUG (MainThread) [custom_components.localtuya.pytuya] [ebb2e815c7c80a5fc4cq0v] Decrypted payload: {}

**Comment by postlund** [comment]
This doesn't sound right:

    Got message type 21930 for unknown listener 43605: TuyaMessage(seqno=43605, cmd=21930, retcode=9, payload=b'', crc=21930)

Is it reproducible every time? I might be able to add some additional debug logs to help troubleshooting.

**Comment by postlund** [comment]
@accelle17 I found a bug in the buffer handing of processed messages. If multiple messages were received at once (e.g. buffered by kernel), processing of the first message would consume the first four bytes of the next message. Not good... I fixed this and pushed an update, maybe you can try it for me?

**Comment by accelle17** [comment]
> Is it reproducible every time? I might be able to add some additional debug logs to help troubleshooting.

This just appears when changing the color. Tried the latest light_hsv branch and still the same.

> 2020-10-19 08:44:05 DEBUG (MainThread) [custom_components.localtuya.pytuya] [ebb2e815c7c80a5fc4cq0v] Sending command heartbeat (device type: type_0a)
2020-10-19 08:44:05 DEBUG (MainThread) [custom_components.localtuya.pytuya] [ebb2e815c7c80a5fc4cq0v] Paylod: b'{}'
2020-10-19 08:44:05 DEBUG (MainThread) [custom_components.localtuya.pytuya] [ebb2e815c7c80a5fc4cq0v] Waiting for sequence number -100
2020-10-19 08:44:05 DEBUG (MainThread) [custom_components.localtuya.pytuya] [ebb2e815c7c80a5fc4cq0v] Got heartbeat response
2020-10-19 08:44:05 DEBUG (MainThread) [custom_components.localtuya.pytuya] [ebb2e815c7c80a5fc4cq0v] Decode payload: b''
2020-10-19 08:44:05 DEBUG (MainThread) [custom_components.localtuya.pytuya] [ebb2e815c7c80a5fc4cq0v] Decrypted payload: {}
2020-10-19 08:44:25 DEBUG (MainThread) [custom_components.localtuya.pytuya] [ebb2e815c7c80a5fc4cq0v] Sending command heartbeat (device type: type_0a)
2020-10-19 08:44:25 DEBUG (MainThread) [custom_components.localtuya.pytuya] [ebb2e815c7c80a5fc4cq0v] Paylod: b'{}'
2020-10-19 08:44:25 DEBUG (MainThread) [custom_components.localtuya.pytuya] [ebb2e815c7c80a5fc4cq0v] Waiting for sequence number -100
2020-10-19 08:44:25 DEBUG (MainThread) [custom_components.localtuya.pytuya] [ebb2e815c7c80a5fc4cq0v] Got heartbeat response
2020-10-19 08:44:25 DEBUG (MainThread) [custom_components.localtuya.pytuya] [ebb2e815c7c80a5fc4cq0v] Decode payload: b''
2020-10-19 08:44:25 DEBUG (MainThread) [custom_components.localtuya.pytuya] [ebb2e815c7c80a5fc4cq0v] Decrypted payload: {}
2020-10-19 08:44:28 DEBUG (MainThread) [custom_components.localtuya.pytuya] [ebb2e815c7c80a5fc4cq0v] Sending command set (device type: type_0a)
2020-10-19 08:44:28 DEBUG (MainThread) [custom_components.localtuya.pytuya] [ebb2e815c7c80a5fc4cq0v] Paylod: b'{"devId":"ebb2e815c7c80a5fc4cq0v","uid":"ebb2e815c7c80a5fc4cq0v","t":"1603068268","dps":{"103":true}}'
2020-10-19 08:44:28 DEBUG (MainThread) [custom_components.localtuya.pytuya] [ebb2e815c7c80a5fc4cq0v] Waiting for sequence number 4
2020-10-19 08:44:28 DEBUG (MainThread) [custom_components.localtuya.pytuya] [ebb2e815c7c80a5fc4cq0v] Got status update
2020-10-19 08:44:28 DEBUG (MainThread) [custom_components.localtuya.pytuya] [ebb2e815c7c80a5fc4cq0v] Decode payload: b'3.3\x00\x00\x00\x00\x00\x00&\x0b\x00\x00\x00\x01\xe8N\x01\x05\xc1\xb2\x92m\xcdN\x0e\xe7\x88\xec\x16\xb5\xefm,\x86\xbd\xf9\xa7\x19\xc8\xf4rQ7\xa9\x9c\xca'
2020-10-19 08:44:28 DEBUG (MainThread) [custom_components.localtuya.pytuya] [ebb2e815c7c80a5fc4cq0v] Decrypted payload: {"dps":{"103":true},"t":63410}
2020-10-19 08:44:28 DEBUG (MainThread) [custom_components.localtuya.pytuya] [ebb2e815c7c80a5fc4cq0v] Got status update
2020-10-19 08:44:28 DEBUG (MainThread) [custom_components.localtuya.pytuya] [ebb2e815c7c80a5fc4cq0v] Decode payload: b'3.3\x00\x00\x00\x00\x00\x00&\x0c\x00\x00\x00\x01j\xa6\xbe\x9b\xd1\xa8{S,\xa5\xb3\x83/\xa4ZVJ3_W5\xc0\xde\xa6\xf5^\x0cC\xe2W\xc4\xc5l\tr\xd57\xf4\xb2\x84\xb6\xea\x8e\x96\x9aF\x9e%\xd6\xfc\xea\xcdb\x00kX\x03\x19\x0f0L\xfct\xd3\x1c\xb62Y}\xcc\x9bX\x08?\x9a#\xd3\x1dz\x15a+Sd$\xaf\xdc\x1e\x92[f)G\x90\xd1\xd4\x1e\xa51\x0e\x93&NUT\x9f/\xbe\x17?\x9b\xd9\x15\xde\x0bI\xe4z^\xfe\xec\xae\xef^\x99\x8e7\xa8O\xe6\xd9\xe3`\x95\xc0\x85\xacL\xfb\xc0\xff\xa7\x04<\x9a\x05&"\xa3\'\x90\xa5\xae\xadI?\xc8\x86\x1e\xb2'

> 2020-10-19 08:44:28 DEBUG (MainThread) [custom_components.localtuya.pytuya] [ebb2e815c7c80a5fc4cq0v] Decrypted payload: {"dps":{"20":true,"21":"colour","22":1000,"24":"007803e80320","25":"000e0d00002e03e802cc00000000","101":1000,"102":true,"103":true,"26":0},"t":63410}
> 
> 2020-10-19 08:44:28 DEBUG (MainThread) [custom_components.localtuya.pytuya] [ebb2e815c7c80a5fc4cq0v] Got message type 12 for unknown listener 7: TuyaMessage(seqno=7, cmd=12, retcode=3089766919, payload=b'', crc=12)
> 
> 2020-10-19 08:44:33 ERROR (MainThread) [custom_components.localtuya.common] Failed to set DP 103 to 1
> Traceback (most recent call last):
>   File "/config/custom_components/localtuya/common.py", line 178, in set_dp
>     await self._interface.set_dp(state, dp_index)
>   File "/config/custom_components/localtuya/pytuya/__init__.py", line 444, in set_dp
>     return await self.exchange(SET, {str(dp_index): value})
>   File "/config/custom_components/localtuya/pytuya/__init__.py", line 406, in exchange
>     msg = await self.dispatcher.wait_for(seqno)
>   File "/config/custom_components/localtuya/pytuya/__init__.py", line 206, in wait_for
>     await asyncio.wait_for(self.listeners[seqno].acquire(), timeout=timeout)
>   File "/usr/local/lib/python3.8/asyncio/tasks.py", line 490, in wait_for
>     raise exceptions.TimeoutError()
> asyncio.exceptions.TimeoutError
> 2020-10-19 08:44:33 ERROR (MainThread) [custom_components.localtuya.light] COLOR: 00f003e80320
> 2020-10-19 08:44:33 DEBUG (MainThread) [custom_components.localtuya.pytuya] [ebb2e815c7c80a5fc4cq0v] Sending command set (device type: type_0a)
> 2020-10-19 08:44:33 DEBUG (MainThread) [custom_components.localtuya.pytuya] [ebb2e815c7c80a5fc4cq0v] Paylod: b'{"devId":"ebb2e815c7c80a5fc4cq0v","uid":"ebb2e815c7c80a5fc4cq0v","t":"1603068273","dps":{"24":"00f003e80320"}}'
> 2020-10-19 08:44:33 DEBUG (MainThread) [custom_components.localtuya.pytuya] [ebb2e815c7c80a5fc4cq0v] Waiting for sequence number 5
> 2020-10-19 08:44:33 DEBUG (MainThread) [custom_components.localtuya.pytuya] [ebb2e815c7c80a5fc4cq0v] Got message type 21930 for unknown listener 43605: TuyaMessage(seqno=43605, cmd=21930, retcode=8, payload=b'', crc=21930)
> 2020-10-19 08:44:33 DEBUG (MainThread) [custom_components.localtuya.pytuya] [ebb2e815c7c80a5fc4cq0v] Got message type 858665728 for unknown listener 0: TuyaMessage(seqno=0, cmd=858665728, retcode=2493696, payload=b'', crc=858665728)
> 2020-10-19 08:44:45 DEBUG (MainThread) [custom_components.localtuya.pytuya] [ebb2e815c7c80a5fc4cq0v] Sending command heartbeat (device type: type_0a)
> 2020-10-19 08:44:45 DEBUG (MainThread) [custom_components.localtuya.pytuya] [ebb2e815c7c80a5fc4cq0v] Paylod: b'{}'
> 2020-10-19 08:44:45 DEBUG (MainThread) [custom_components.localtuya.pytuya] [ebb2e815c7c80a5fc4cq0v] Waiting for sequence number -100
> 2020-10-19 08:44:50 ERROR (MainThread) [custom_components.localtuya.pytuya] [ebb2e815c7c80a5fc4cq0v] Heartbeat failed (), disconnecting
> Traceback (most recent call last):
>   File "/config/custom_components/localtuya/pytuya/__init__.py", line 345, in heartbeat_loop
>     await self.heartbeat()
>   File "/config/custom_components/localtuya/pytuya/__init__.py", line 434, in heartbeat
>     return await self.exchange(HEARTBEAT)
>   File "/config/custom_components/localtuya/pytuya/__init__.py", line 406, in exchange
>     msg = await self.dispatcher.wait_for(seqno)
>   File "/config/custom_components/localtuya/pytuya/__init__.py", line 206, in wait_for
>     await asyncio.wait_for(self.listeners[seqno].acquire(), timeout=timeout)
>   File "/usr/local/lib/python3.8/asyncio/tasks.py", line 490, in wait_for
>     raise exceptions.TimeoutError()
> asyncio.exceptions.TimeoutError
> 2020-10-19 08:44:50 DEBUG (MainThread) [custom_components.localtuya.pytuya] [ebb2e815c7c80a5fc4cq0v] Stopped heartbeat loop
> 2020-10-19 08:44:50 DEBUG (MainThread) [custom_components.localtuya.pytuya] [ebb2e815c7c80a5fc4cq0v] Closing connection
> 2020-10-19 08:44:50 DEBUG (MainThread) [custom_components.localtuya.pytuya] [ebb2e815c7c80a5fc4cq0v] Connection lost: None
> 2020-10-19 08:44:50 DEBUG (MainThread) [custom_components.localtuya.pytuya] [ebb2e815c7c80a5fc4cq0v] Closing connection
> 2020-10-19 08:44:50 DEBUG (MainThread) [custom_components.localtuya.common] Disconnected from ebb2e815c7c80a5fc4cq0v: None
> 2020-10-19 08:44:50 DEBUG (MainThread) [custom_components.localtuya.common] Connecting to 192.168.20.49 (ebb2e815c7c80a5fc4cq0v)
> 2020-10-19 08:44:50 DEBUG (MainThread) [custom_components.localtuya.common] Waiting 0 seconds before connecting
> 2020-10-19 08:44:50 DEBUG (MainThread) [custom_components.localtuya.common] Connecting to 192.168.20.49
> 2020-10-19 08:44:50 DEBUG (MainThread) [custom_components.localtuya.pytuya] [ebb2e815c7c80a5fc4cq0v] Started heartbeat loop
> 2020-10-19 08:44:50 DEBUG (MainThread) [custom_components.localtuya.pytuya] [ebb2e815c7c80a5fc4cq0v] Sending command heartbeat (device type: type_0a)
> 2020-10-19 08:44:50 DEBUG (MainThread) [custom_components.localtuya.pytuya] [ebb2e815c7c80a5fc4cq0v] Paylod: b'{}'
> 2020-10-19 08:44:50 DEBUG (MainThread) [custom_components.localtuya.pytuya] [ebb2e815c7c80a5fc4cq0v] Waiting for sequence number -100
> 2020-10-19 08:44:50 DEBUG (MainThread) [custom_components.localtuya.common] Retrieving initial state
> 2020-10-19 08:44:50 DEBUG (MainThread) [custom_components.localtuya.pytuya] [ebb2e815c7c80a5fc4cq0v] Sending command status (device type: type_0a)
> 2020-10-19 08:44:50 DEBUG (MainThread) [custom_components.localtuya.pytuya] [ebb2e815c7c80a5fc4cq0v] Paylod: b'{"gwId":"ebb2e815c7c80a5fc4cq0v","devId":"ebb2e815c7c80a5fc4cq0v"}'
> 2020-10-19 08:44:50 DEBUG (MainThread) [custom_components.localtuya.pytuya] [ebb2e815c7c80a5fc4cq0v] Waiting for sequence number 1
> 2020-10-19 08:44:51 DEBUG (MainThread) [custom_components.localtuya.pytuya] [ebb2e815c7c80a5fc4cq0v] Got heartbeat response
> 2020-10-19 08:44:51 DEBUG (MainThread) [custom_components.localtuya.pytuya] [ebb2e815c7c80a5fc4cq0v] Decode payload: b''
> 2020-10-19 08:44:51 DEBUG (MainThread) [custom_components.localtuya.pytuya] [ebb2e815c7c80a5fc4cq0v] Decrypted payload: {}
> 2020-10-19 08:44:51 DEBUG (MainThread) [custom_components.localtuya.pytuya] [ebb2e815c7c80a5fc4cq0v] Dispatching sequence number 1
> 2020-10-19 08:44:51 DEBUG (MainThread) [custom_components.localtuya.pytuya] [ebb2e815c7c80a5fc4cq0v] Decode payload: b'j\xa6\xbe\x9b\xd1\xa8{S,\xa5\xb3\x83/\xa4ZVJ3_W5\xc0\xde\xa6\xf5^\x0cC\xe2W\xc4\xc5l\tr\xd57\xf4\xb2\x84\xb6\xea\x8e\x96\x9aF\x9e%zHw\x01\x13\xbblSh\x00\xb0\xca:\x86ti\x1c\xb62Y}\xcc\x9bX\x08?\x9a#\xd3\x1dz\x15a+Sd$\xaf\xdc\x1e\x92[f)G\x90\xd1\xd4\xd4\x82!\xa7\x06R\xd1r\x88\x0e\xa5\xaf\x13\x9a\xd2\x08;\xcc`I\x1fT&\x8cL~\x95\xe4+\xd8\x088&\xc5v\xf2\xc0\xd4\xc92\xad\x12\x1c7\xae\x01\x02\x0c'
> 2020-10-19 08:44:51 DEBUG (MainThread) [custom_components.localtuya.pytuya] [ebb2e815c7c80a5fc4cq0v] Decrypted payload: {"dps":{"20":true,"21":"colour","22":1000,"24":"00f003e80320","25":"000e0d00002e03e802cc00000000","26":0,"101":1000,"102":true,"103":true}}
> 2020-10-19 08:45:11 DEBUG (MainThread) [custom_components.localtuya.pytuya] [ebb2e815c7c80a5fc4cq0v] Sending command heartbeat (device type: type_0a)
> 2020-10-19 08:45:11 DEBUG (MainThread) [custom_components.localtuya.pytuya] [ebb2e815c7c80a5fc4cq0v] Paylod: b'{}'
> 2020-10-19 08:45:11 DEBUG (MainThread) [custom_components.localtuya.pytuya] [ebb2e815c7c80a5fc4cq0v] Waiting for sequence number -100

**Comment by postlund** [comment]
@accelle17 My bad, I pushed the update to wrong branch... Can you try updating and run again?

**Comment by accelle17** [comment]
> @accelle17 My bad, I pushed the update to wrong branch... Can you try updating and run again?

Looks good, no error now and the change reflects instantaneous on the light and ui. It's able to change hue and saturation. Looking forward on the brightness in the future 👍

**Comment by postlund** [comment]
> > @accelle17 My bad, I pushed the update to wrong branch... Can you try updating and run again?
> 
> Looks good, no error now and the change reflects instantaneous on the light and ui. It's able to change hue and saturation. Looking forward on the brightness in the future 👍

I have implemented brightness as well, but I'm not sure it works. Would be great if you tried it.

**Comment by accelle17** [comment]
> I have implemented brightness as well, but I'm not sure it works. Would be great if you tried it.

The UI just show the color wheel and no brightness slider. I didn't fill up the brightness since there's no dedicated DP for it on my device. The brightness is mapped to the last 4 digit of DP24.

![image](https://user-images.githubusercontent.com/20294546/96410890-330ef500-121a-11eb-996d-59a994a750c7.png)

**Comment by postlund** [comment]
Ah, then I understand. Still learning about the quirks. I can certainly fix that. In the meantime you can try setting the brightness option to any DP as a test. The last four bytes are used for brightness. You will not be able to unset this and will have to re-add the device again though.

**Comment by postlund** [comment]
@accelle17 Pushed an update, hopefully brightness should work out-of-the-box now.

**Comment by accelle17** [comment]
> @accelle17 Pushed an update, hopefully brightness should work out-of-the-box now.

it's working 👍

**Comment by postlund** [comment]
> > @accelle17 Pushed an update, hopefully brightness should work out-of-the-box now.
> 
> it's working 👍

Perfect! I'm gonna split out the pytuya bug fixes to a separate PR and make some tweaks, then maybe we can try to merge HSV support before moving on to RGB (and getting bug reports for HSV...).

**Comment by postlund** [comment]
@accelle17 The pytuya fixes are merged separately now and I've made a few tweaks. Can you try removing, adding the device and try again just to be sure that it works? After that (and review from @rospogrigio) we can merge it.

**Comment by accelle17** [comment]
sorry, you mean the light_hsv branch right?
Unfortunately, I'm not able to control the colored light part after the change. I have removed the device, restarted and re-add it.

Here's the logs:

> 2020-10-19 17:18:50 DEBUG (MainThread) [custom_components.localtuya.common] Connecting to 192.168.20.49 (ebb2e815c7c80a5fc4cq0v)
2020-10-19 17:18:50 DEBUG (MainThread) [custom_components.localtuya.common] Waiting 0 seconds before connecting
2020-10-19 17:18:50 DEBUG (MainThread) [custom_components.localtuya.common] Connecting to 192.168.20.49
2020-10-19 17:18:50 DEBUG (MainThread) [custom_components.localtuya.pytuya] [ebb2e815c7c80a5fc4cq0v] Started heartbeat loop
2020-10-19 17:18:50 DEBUG (MainThread) [custom_components.localtuya.pytuya] [ebb2e815c7c80a5fc4cq0v] Sending command heartbeat (device type: type_0a)
2020-10-19 17:18:50 DEBUG (MainThread) [custom_components.localtuya.pytuya] [ebb2e815c7c80a5fc4cq0v] Send payload: b'{}'
2020-10-19 17:18:50 DEBUG (MainThread) [custom_components.localtuya.pytuya] [ebb2e815c7c80a5fc4cq0v] Waiting for sequence number -100
2020-10-19 17:18:50 DEBUG (MainThread) [custom_components.localtuya.common] Retrieving initial state
2020-10-19 17:18:50 DEBUG (MainThread) [custom_components.localtuya.pytuya] [ebb2e815c7c80a5fc4cq0v] Sending command status (device type: type_0a)
2020-10-19 17:18:50 DEBUG (MainThread) [custom_components.localtuya.pytuya] [ebb2e815c7c80a5fc4cq0v] Send payload: b'{"gwId":"ebb2e815c7c80a5fc4cq0v","devId":"ebb2e815c7c80a5fc4cq0v"}'
2020-10-19 17:18:50 DEBUG (MainThread) [custom_components.localtuya.pytuya] [ebb2e815c7c80a5fc4cq0v] Waiting for sequence number 1
2020-10-19 17:18:51 DEBUG (MainThread) [custom_components.localtuya.pytuya] Dispatching message TuyaMessage(seqno=0, cmd=9, retcode=0, payload=b'', crc=2958142211)
2020-10-19 17:18:51 DEBUG (MainThread) [custom_components.localtuya.pytuya] [ebb2e815c7c80a5fc4cq0v] Got heartbeat response
2020-10-19 17:18:51 DEBUG (MainThread) [custom_components.localtuya.pytuya] [ebb2e815c7c80a5fc4cq0v] Decrypted payload: {}
2020-10-19 17:18:51 DEBUG (MainThread) [custom_components.localtuya.pytuya] Dispatching message TuyaMessage(seqno=1, cmd=10, retcode=0, payload=b'\xa5\xfb.n\x013\xa0\xc4\xad\xf0\xa0H<\xe1\xd6\x18\xda\xb6s\x1d\x97\xca\xda\xed\xda\xeb\x16OK\x87\x96_l\tr\xd57\xf4\xb2\x84\xb6\xea\x8e\x96\x9aF\x9e%\xd0\xc9V\xe7\xdd^eP\xa5\xd2\x18N\xb0\x1c\x18}\x1c\xb62Y}\xcc\x9bX\x08?\x9a#\xd3\x1dz\x15a+Sd$\xaf\xdc\x1e\x92[f)G\x90\xd1\xd4\xd4\x82!\xa7\x06R\xd1r\x88\x0e\xa5\xaf\x13\x9a\xd2\x08\x9eP6\n1\x88LL\xa9I\xf8x\xceb<\xc1]\x00\xfeE\x0e\x84\x1fC0\xdeW\x81\xee4\x1bI', crc=480149476)
2020-10-19 17:18:51 DEBUG (MainThread) [custom_components.localtuya.pytuya] [ebb2e815c7c80a5fc4cq0v] Dispatching sequence number 1
2020-10-19 17:18:51 DEBUG (MainThread) [custom_components.localtuya.pytuya] [ebb2e815c7c80a5fc4cq0v] Decrypted payload: {"dps":{"20":false,"21":"white","22":1000,"24":"015903e803e8","25":"000e0d00002e03e802cc00000000","26":0,"101":1000,"102":false,"103":false}}
2020-10-19 17:18:51 WARNING (SyncWorker_14) [custom_components.localtuya.common] Entity light.aerisroom_nebula_light is requesting unknown DPS index None
2020-10-19 17:18:57 DEBUG (MainThread) [custom_components.localtuya.pytuya] [ebb2e815c7c80a5fc4cq0v] Sending command set (device type: type_0a)
2020-10-19 17:18:57 DEBUG (MainThread) [custom_components.localtuya.pytuya] [ebb2e815c7c80a5fc4cq0v] Send payload: b'{"devId":"ebb2e815c7c80a5fc4cq0v","uid":"ebb2e815c7c80a5fc4cq0v","t":"1603099137","dps":{"20":true}}'
2020-10-19 17:18:57 DEBUG (MainThread) [custom_components.localtuya.pytuya] [ebb2e815c7c80a5fc4cq0v] Waiting for sequence number 2
2020-10-19 17:18:57 DEBUG (MainThread) [custom_components.localtuya.pytuya] Dispatching message TuyaMessage(seqno=0, cmd=8, retcode=0, payload=b'3.3\x00\x00\x00\x00\x00\x00&\xb4\x00\x00\x00\x01j\xa6\xbe\x9b\xd1\xa8{S,\xa5\xb3\x83/\xa4ZV\x9a\xfbHk@\x01s]\xf5WX0\xb4\x8eG\xd5s\x15\xca\xfd\x7f\xd8\x1b;\xed\t\x00+\xe0c6\x85l})\xe0\xcbJf\x9aD\xecd \xaf\xd7@\xa2]U\xa3W7\xc5\x9dp\xd6\xf0bi\x0f=\xef\xb8\xed\xca\\\x97\x99s\x86\x01\x827c.\x9a\xd3`\x16T\x14\xc2#\x01)\xd6\x8cc\xba\xb6\xa3\xb4\xaf]\xec\xb7\x15\xef\x1e\xf0-\x00!@S\x89\x87\xbft\xf8\xb7\xec\xa1c\xc5\x97\x0bD"u\xbce\x1b\x8a\xd2\x17\x94\x9f\xe3\x7f2\x19voW\xdf\xae\x00m\xa3\xc5\x01\xae', crc=1229686264)
2020-10-19 17:18:57 DEBUG (MainThread) [custom_components.localtuya.pytuya] [ebb2e815c7c80a5fc4cq0v] Got status update
2020-10-19 17:18:57 DEBUG (MainThread) [custom_components.localtuya.pytuya] [ebb2e815c7c80a5fc4cq0v] Decrypted payload: {"dps":{"20":true,"21":"white","22":1000,"24":"015903e803e8","25":"000e0d00002e03e802cc00000000","101":1000,"102":false,"103":false,"26":0},"t":94278}
2020-10-19 17:18:57 WARNING (SyncWorker_58) [custom_components.localtuya.common] Entity light.aerisroom_nebula_light is requesting unknown DPS index None
2020-10-19 17:18:57 DEBUG (MainThread) [custom_components.localtuya.pytuya] Dispatching message TuyaMessage(seqno=0, cmd=8, retcode=0, payload=b'3.3\x00\x00\x00\x00\x00\x00&\xb5\x00\x00\x00\x01j\xa6\xbe\x9b\xd1\xa8{S,\xa5\xb3\x83/\xa4ZV\x9a\xfbHk@\x01s]\xf5WX0\xb4\x8eG\xd5s\x15\xca\xfd\x7f\xd8\x1b;\xed\t\x00+\xe0c6\x85l})\xe0\xcbJf\x9aD\xecd \xaf\xd7@\xa2]U\xa3W7\xc5\x9dp\xd6\xf0bi\x0f=\xef\xb8\xed\xca\\\x97\x99s\x86\x01\x827c.\x9a\xd3`\x16T\x14\xc2#\x01)\xd6\x8cc\xba\xb6\xa3\xb4\xaf]\xec\x02\x05\xce\xfb)\x1dG\xa8\xe1\xc8\xe0\xc5\x85\x8e}$\xe4t\x13o?\xee\xb3\xbc\xfd_\x96\xdd\x97\xff\xddp\xcc|\x91\xe2\xcb(\xf3Pr\xe2\xd3jE\xdb\x94\xd2', crc=1775104583)
2020-10-19 17:18:57 DEBUG (MainThread) [custom_components.localtuya.pytuya] [ebb2e815c7c80a5fc4cq0v] Got status update
2020-10-19 17:18:57 DEBUG (MainThread) [custom_components.localtuya.pytuya] [ebb2e815c7c80a5fc4cq0v] Decrypted payload: {"dps":{"20":true,"21":"white","22":1000,"24":"015903e803e8","25":"000e0d00002e03e802cc00000000","101":1000,"102":true,"103":true,"26":0},"t":94278}
2020-10-19 17:18:57 WARNING (SyncWorker_59) [custom_components.localtuya.common] Entity light.aerisroom_nebula_light is requesting unknown DPS index None
2020-10-19 17:18:57 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 283, in async_update_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 322, in _async_write_ha_state
    attr.update(self.state_attributes or {})
  File "/usr/src/homeassistant/homeassistant/components/light/__init__.py", line 439, in state_attributes
    data[ATTR_BRIGHTNESS] = self.brightness
  File "/config/custom_components/localtuya/light.py", line 96, in brightness
    return map_range(
  File "/config/custom_components/localtuya/light.py", line 42, in map_range
    mapped = (value - from_lower) * (to_upper - to_lower) / (
TypeError: unsupported operand type(s) for -: 'NoneType' and 'int'
2020-10-19 17:18:57 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 283, in async_update_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 322, in _async_write_ha_state
    attr.update(self.state_attributes or {})
  File "/usr/src/homeassistant/homeassistant/components/light/__init__.py", line 439, in state_attributes
    data[ATTR_BRIGHTNESS] = self.brightness
  File "/config/custom_components/localtuya/light.py", line 96, in brightness
    return map_range(
  File "/config/custom_components/localtuya/light.py", line 42, in map_range
    mapped = (value - from_lower) * (to_upper - to_lower) / (
TypeError: unsupported operand type(s) for -: 'NoneType' and 'int'
2020-10-19 17:18:57 DEBUG (MainThread) [custom_components.localtuya.pytuya] Dispatching message TuyaMessage(seqno=2, cmd=7, retcode=0, payload=b'', crc=416269786)
2020-10-19 17:18:57 DEBUG (MainThread) [custom_components.localtuya.pytuya] [ebb2e815c7c80a5fc4cq0v] Dispatching sequence number 2
2020-10-19 17:18:57 DEBUG (MainThread) [custom_components.localtuya.pytuya] [ebb2e815c7c80a5fc4cq0v] Decrypted payload: {}


>

**Comment by postlund** [comment]
Did you remove and re-add? I changed the name of an option so it needs to be migrated.

**Comment by accelle17** [comment]
yes, removed, copy the light_hsv branch, restarted and re-add. I mapped the same DP.

**Comment by dlashua** [comment]
Not sure if it helps any but my bulb reports like this:
```
{ devId: '2784505598f4abfab74b',
  dps:
   { '1': true,
     '2': 'colour',
     '3': 255,
     '4': 0,
     '5': 'ff00ff012cffff',
     '6': 'bd76000168ffff',
     '7': 'ffff500100ff00',
     '8': 'ffff8003ff000000ff000000ff000000000000000000',
     '9': 'ffff5001ff0000',
     '10': 'ffff0505ff000000ff00ffff00ff00ff0000ff000000' } }

```

I believe color is dps5 with a value like "rrggbb0hhhssvv"

**Comment by postlund** [comment]
@dlashua That looks about right. I'll get cracking on RGB soon I hope. Will try to fix the minor bug @accelle17 found first.

**Comment by postlund** [comment]
Also, maybe you can try changing this line:

https://github.com/rospogrigio/localtuya/blob/c1878f82e20d7c5d7a24494b326ca55853fad889/custom_components/localtuya/pytuya/__init__.py#L96

By replacing `uid` with `gwId` and try tuyadebug again?

**Comment by ultratoto14** [comment]
@dlashua perhaps you can check this PR and report if it works for you.
If you use config_flow, do not forget to set max brightness value to 255, if you use yaml check the README of this PR, you should have a configuration like:
```yaml
id: 1
brightness: 3
color_temp: 4
color_mode: 2
color: 5
brightness_upper: 255
brightness_lower: 25
```

**Comment by postlund** [comment]
Since both HSV and RGB support is merged now, can we close this issue and open new issues for individual problems? Just to avoid long running issues that tries to cover every part of everything...

**Comment by ChaoticBD** [comment]
thanks, work greate for me.

**Comment by dlashua** [comment]
@ultratoto14 tested this in a dev instance and my light works perfectly. I'll but the latest code in my production instance later today to give it a real work out.

THANKS!

**Comment by postlund** [comment]
Out with a bang! 💥

**Comment by drinfernoo** [comment]
> Not sure if it helps any but my bulb reports like this:
> 
> ```
> { devId: '2784505598f4abfab74b',
>   dps:
>    { '1': true,
>      '2': 'colour',
>      '3': 255,
>      '4': 0,
>      '5': 'ff00ff012cffff',
>      '6': 'bd76000168ffff',
>      '7': 'ffff500100ff00',
>      '8': 'ffff8003ff000000ff000000ff000000000000000000',
>      '9': 'ffff5001ff0000',
>      '10': 'ffff0505ff000000ff00ffff00ff00ff0000ff000000' } }
> ```
> 
> I believe color is dps5 with a value like "rrggbb0hhhssvv"

Were you ever able to figure out what 6-10 are for?

**Comment by drinfernoo** [comment]
For anyone coming around to this issue later on, these are the values that worked for me, cross a couple different bulbs:

For DPS 1-10 bulbs:
```
ID - 1
Color Mode - 2
Brightness - 3
Color Temperature - 4
Color - 5
Scene - 6
```

and for DPS 20-26 bulbs:
```
ID - 20
Color Mode - 21
Brightness - 22
Color Temperature - 23
Color - 24
Scene - 25
```

YMMV in any case, but this might be a good guideline for most bulbs out there... I've got these values for Teckin, Merkury, and even something like [this "Music Star Light"](https://www.amazon.com/Projector-Lighting-Bluetooth-Sound-Activated-Birthday/dp/B07X1J9L6S), and have helped a few people with other brands that ended up with the same values.

**Comment by DigaumSpider** [comment]
> For anyone coming around to this issue later on, these are the values that worked for me, cross a couple different bulbs:
> 
> For DPS 1-10 bulbs:
> 
> ```
> ID - 1
> Color Mode - 2
> Brightness - 3
> Color Temperature - 4
> Color - 5
> Scene - 6
> ```
> 
> and for DPS 20-26 bulbs:
> 
> ```
> ID - 20
> Color Mode - 21
> Brightness - 22
> Color Temperature - 23
> Color - 24
> Scene - 25
> ```
> 
> YMMV in any case, but this might be a good guideline for most bulbs out there... I've got these values for Teckin, Merkury, and even something like [this "Music Star Light"](https://www.amazon.com/Projector-Lighting-Bluetooth-Sound-Activated-Birthday/dp/B07X1J9L6S), and have helped a few people with other brands that ended up with the same values.

You, Sir, are a gentleman and a scholar.  Wish I could buy you a beer, after spending so many hours trying to figure this crap out as a newstarter!

This worked for my Mirabella Genio RGBW and White downlights working in local tuya mode!

Thanks!!!!

**Comment by thebadluck** [comment]
> For anyone coming around to this issue later on, these are the values that worked for me, across a couple different bulbs:
> 
> For DPS 1-10 bulbs:
> 
> ```
> ID - 1
> Color Mode - 2
> Brightness - 3
> Color Temperature - 4
> Color - 5
> Scene - 6
> ```
> 
> and for DPS 20-26 bulbs:
> 
> ```
> ID - 20
> Color Mode - 21
> Brightness - 22
> Color Temperature - 23
> Color - 24
> Scene - 25
> ```
> 


Worked like a champ!

**Comment by zcworld** [comment]
> > For anyone coming around to this issue later on, these are the values that worked for me, across a couple different bulbs:
> > For DPS 1-10 bulbs:
> > ```
> > ID - 1
> > Color Mode - 2
> > Brightness - 3
> > Color Temperature - 4
> > Color - 5
> > Scene - 6
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > and for DPS 20-26 bulbs:
> > ```
> > ID - 20
> > Color Mode - 21
> > Brightness - 22
> > Color Temperature - 23
> > Color - 24
> > Scene - 25
> > ```
> 
> Worked like a champ!


Killer ... Love it was going around in loops

**Comment by guilhermebera** [comment]
> 

It solved my problem too! I was getting "unavailable" or just able to turn on/off, now everything works.
